[package]
name = "halo2_fft_benchmark"
version = "0.0.1"
authors = ["The Tachyon Authors <tachyon-discuss@kroma.network>"]
edition = "2021"
rust-version = "1.56.1"
description = """
Halo2 FFT Benchmark
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/kroma-network/tachyon"
documentation = "https://docs.rs/halo2_benchmark"
readme = "README.md"
categories = ["cryptography"]
keywords = ["tachyon", "benchmark", "halo2"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/kroma-network/halo2.git", rev = "be2e64f" }
tachyon_rs = { path = "../../../tachyon/rs" }
