[package]
name = "plonky3_fri_benchmark"
version = "0.0.1"
authors = ["The Tachyon Authors <tachyon-discuss@kroma.network>"]
edition = "2021"
description = """
Plonky3 FRI Benchmark
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/kroma-network/tachyon"
readme = "README.md"
categories = ["cryptography"]
keywords = ["tachyon", "benchmark", "plonky3"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-baby-bear = "0.1.3-succinct"
p3-challenger = "0.1.3-succinct"
p3-commit = "0.1.3-succinct"
p3-dft = "0.1.3-succinct"
p3-field = "0.1.3-succinct"
p3-fri = "0.1.3-succinct"
p3-matrix = "0.1.3-succinct"
p3-merkle-tree = "0.1.3-succinct"
p3-poseidon2 = "0.1.3-succinct"
p3-symmetric = "0.1.3-succinct"
p3-util = "0.1.3-succinct"
tachyon_rs = { path = "../../../tachyon/rs" }
zkhash = { git = "https://github.com/HorizenLabs/poseidon2.git", rev = "bb476b9" }
