name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bazel_config: linux
          - os: macos-latest
            bazel_config: macos_x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Setup Python and Install numpy
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install numpy
        run: python -m pip install numpy

      - name: Install OpenMP
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libomp-dev

      - name: Build
        run: bazel build -c fastbuild --config ${{ matrix.bazel_config }} //...

      - name: Test Tachyon
        run: bazel test -c fastbuild --config ${{ matrix.bazel_config }} --test_output=errors --test_tag_filters -benchmark,-manual,-cuda,-rust //...

      - name: Test OpenMP
        if: matrix.os == 'ubuntu-latest'
        run: bazel test -c fastbuild --config linux --//:has_openmp --test_output=errors --test_tag_filters -benchmark,-manual,-cuda,-rust //...

      - name: Test Node Binding
        run: |
          cd tachyon/node/test
          bazel test --config ${{ matrix.bazel_config }} --test_output=errors //...

      - name: Test Py Binding
        # TODO(chokobole): Remove this condition once we fix https://github.com/kroma-network/tachyon/issues/197.
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd tachyon/py/test
          bazel test --config ${{ matrix.bazel_config }} --test_output=errors //...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --all

      - name: Setup Python for cpplint
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        if: github.event_name == 'pull_request'
        run: git diff --name-only HEAD origin/${{ github.base_ref }} | xargs cpplint --filter=-legal/copyright,-whitespace/line_length,-build/namespaces,-runtime/references

      - name: Run clang-format lint
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "17"
          check-path: "."
